yolo_dir: C:\yolov5
python: python
raw_images: C:\ML_Software\active_learning\data\downloads

# reccommended to change outdir for each run if using different images/params!!!
output_dir: C:\ML_Software\active_learning\data
weights: C:\yolov5\runs\train\63ImageTraim_19Mar_(S300)\weights\best.pt
cache: False

# yaml config describing the training data and classes
workers: 6

BATCH_SIZE: 8
EPOCHS: 500

TILE_SIZE: 416
STRIDE: 104

# training Dataset
path: C:\ML_Software\training
train:
  # - C:\yoloDatasets\trainFinal\images
  - C:\ML_Software\active_learning\data\images
val:
  # - C:\ML_Software\MoretonVal\images
names:
  0: boat
  1: movingBoat
