# Configuration for Validation/Analysis Runs
path: /Users/charlieturner/Documents/CountingBoats/case_studies/TestMoreton
weights: /Users/charlieturner/Documents/CountingBoats/data/NN_weights.pt
# weights: /Users/charlieturner/Desktop/Yolov5l.pt
device: mps

raw_images: /Users/charlieturner/Documents/CountingBoats/case_studies/TestMoreton/RawImages # Folders as downloaded from Planet (extracted zips)

# Auxiliary Paths (relative to run folder, or absolute if using existing)
# These paths either exist (and are used) or are created (and used) by the run
pngs: /Users/charlieturner/Documents/CountingBoats/case_studies/TestMoreton # Pngs for the tif files
segmented_images: /Users/charlieturner/Documents/CountingBoats/case_studies/TestMoreton/images # Segmented images
labels: /Users/charlieturner/Documents/CountingBoats/case_studies/TestMoreton/labels # Labels for the images
classifications: /Users/charlieturner/Documents/CountingBoats/case_studies/TestMoreton/Classifications # Classifications for the images
# classifications: classifications

img_size: 416
img_stride: 104

tasks:
  # These 4 are not required if have been done before (and above paths are absolute and exist)
  prepare: False # Prepare for labelling
  segment: False # Segment images/labels
  run_detection: False # Run the classifier

  analyse:
    # Main analysis step: cluster and compare
    compare_detections_to_ground_truth: True # Cluster and compare results to ground truth (have to do this for all analysis below)

    # Supplementary analysis, not all implemented
    plots:
      confusion_matrix: False
      boat_count_compare: False
      precision_recall: False
      roc: False
      mAP_50: False
      mAP_75: False
      mAP_90: False
    images:
      all_mistakes: False # Collate all mistakes into images with comparison
      subimage_confidence: 10 # Show confidence of detection for all subimages of a given boat (number of random boats to do this for)
      coverage_heatmap: False
