# Likely Need Changing
# yolo_dir : C:\yolov5-master                             # installation directory of yolov5
# python   : C:\Users\turner30\AppData\Local\Programs\Python\Python38\python # path to python executable (probably just 'python')
yolo_dir: C:\yolov5
python: python
proj_root: C:\ML_Software # root of project (where this file is)
weights: ./data/NN_weights.pt # yolov5 weights file
planet:
  api_key:
    ENV # If 'ENV', use env file (so doesn't go to version control)
    # If api_key is 'ENV', there must be a '.env' file in the same directory as this file with PLANET_API_KEY={your_api_key}
output_dir: ./results
tif_dir: .\images\RawImages
download_dir: .\images\downloads

# Technical Configuration
# Size of tiles to split images into for processing
TILE_SIZE: 416
# I do beleive YOLO will resize images to work, but this should be the same as the YOLO model was trained on
STRIDE: 104 # Stride for overlapping tiles

CONFIDENCE_THRESHOLD: 0.5 # Discard any detections below this

# Distance cutoffs for determining if a boat is the same in two frames
STAT_DISTANCE_CUTOFF_PIX: 3
MOVING_DISTANCE_CUTOFF_PIX: 6
# The lat/long cutoff should be roughly related to the resolution of the images
# For 3m resolution, 10 pix is roughly 30m. At approx -27 deg lat, this is approx 0.0003 degrees.
STAT_DISTANCE_CUTOFF_LATLONG: 0.00025
MOVING_DISTANCE_CUTOFF_LATLONG: 0.0003

# Automation Configuration
AUTO_MODE: "batch" # 'batch' or 'single' - whether to run in batch mode or all history at once
# HISTORY_LENGTH: 3 # Days in the past to fetch (new) imagery for
# OR (HISTORY_LENGTH takes precedence):
START_DATE: "2016-07-01" # Date to start fetching imagery from YYYY-MM-DD
END_DATE: "2019-07-01" # Date to stop fetching imagery from YYYY-MM-DD
BATCH_SIZE: 7 # Number of days to process (order -> download -> infer) before moving on to next batch

ALLOWED_CLOUD_COVER: 0.8 # Fraction of image which can be covered by clouds and still be added to day's composite
MINIMUM_AREA_COVERAGE: 0.0 # Fraction of interest area which must be present to download
AOIS: "moreton" # Specific AOIs to fetch imagery for (comma separated names of polygons) or "all" for all AOIs in data/polygons

HEATMAP_SIZE: 1000 # Size of each heatmap square (in meters)

