yolo_dir: C:\yolov5
python: python
raw_images: C:\ML_Software\active_learning\data\downloads

# reccommended to change outdir for each run if using different images/params!!!
output_dir: C:\ML_Software\active_learning\data
weights: yolov5s.pt
cache: False

# yaml config describing the training data and classes
# NOTE: could definitely automate this after splitting images later
data: ./data/training_boats.yaml
workers: 6

BATCH_SIZE: 32
EPOCHS: 500

TILE_SIZE: 416
STRIDE: 104

# training Dataset
path: C:\ML_Software\training
train:
  - C:\ML_Software\active_learning\data\images
  - C:\yoloDatasets\trainFinal\images
val:
  - U:\Research\Projects\sef\livingplayingmb\Data\BoatDetectionTraining\val\images
names:
  0: boat
  1: movingBoat
