classifications: Classifications
labels: Labels
overwrite_auxiliaries: false
path: /Users/charlieturner/Documents/CountingBoats/case_studies/TestMoreton
raw_images: RawImages
segmented_images: SegmentedImages
tasks:
  analyse:
    compare: true
    images:
      all_mistakes: true
      subimage_confidence: true
    plots:
      confusion_matrix: true
      mAP_50: true
      mAP_75: true
      mAP_90: true
      precision_recall: true
      roc: true
  count: true
  prepare: false
  segment: false
use_existing_auxiliaries:
- segmented_images: SegmentedImages
- classifications: Classifications
- labels: Labels
weights: /Users/charliturner/Desktop/Yolov5l.pt
